### ISSUE TITLE
Have `xrt_teem` return a `namedtuple`

### ISSUE THREAD

**Issue by namurphy** [HinodeXRT/xrtpy#146]

**Comment by jslavin** [comment]
So then you'd like us to return a namedtuple of Maps, right? That wouldn't be hard to implement.

**Comment by namurphy** [comment]
Yep!  The pattern I was thinking of would be something like 
```python
from collections import namedtuple

FunctionOutput = namedtuple('FunctionOutput', ['x', 'y'])

def f(a, b):
    x = a + 1
    y = b + 2
    return FunctionOutput(x, y)
```
This would let us retain backward compatibility, but would also let us do things like:
```pycon
>>> output = f(1, 2)
>>> output.x
2
>>> output.y
4
```

**Comment by jslavin** [comment]
This has been done in PR #148
