### ISSUE TITLE
Use files from remote server rather than storing them directly in the repository

### ISSUE THREAD

**Issue by wtbarnes** [HinodeXRT/xrtpy#170]
### Description

When cloning the repository, I noticed that the total size of the repository is now over 150 MB. My understanding is that this is also preventing releases due to the upper limit of package sizes on PyPI being 60 MB. 

To remedy this, I would suggest making use of the [data manager functionality in `sunpy`](https://docs.sunpy.org/en/stable/how_to/remote_data_manager.html). Below, I've listed a few files that I think this could easily apply to:

- `data/XRT20170324_151721.0.PSF560.fits` in `xrt_deconvolve`
- `data/XRT20170324_161721.0.PSF1000.fits` in `xrt_deconvolve`
- All files in `data/leak_fits` in `xrt_remove_lightleak`

I'm still looking through the repository and will continue to add candidates to this list.

**Comment by wtbarnes** [comment]
For an example of how this is done in `aiapy`, see here: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/blob/main/aiapy/response/channel.py?ref_type=heads#L89

**Comment by wtbarnes** [comment]
The two URLs for the SSW mirrors that we should target are:

- https://sohoftp.nascom.nasa.gov/solarsoft/
- https://hesperia.gsfc.nasa.gov/ssw/

**Comment by jslavin** [comment]
This has been done.
