### ISSUE TITLE
Function naming conventions

### ISSUE THREAD

**Issue by wtbarnes** [HinodeXRT/xrtpy#181]
### Description

There are several functions that are prepended with `xrt_`. I assume this is to be consistent with what they are called in IDL. These include:

- `xrt_remove_lightleak`
- `xrt_deconvolve`
- `xrt_teem`

I would suggest removing the `xrt_` that is prepended to each filename. In IDL, such naming conventions are needed because there is no concept of a namespace. However, all of these functions live within the `xrtpy` package and thus it is not necessary to explicitly say in the function name that these are associated with XRT/`xrtpy`.

Additionally, I find the name "teem" very confusing/ambiguous. I realize again that this is to be consistent with the function name in IDL, but this name will not be meaningful to new users/those who have never used the IDL tools. I would suggest a more descriptive name for this function, something along the lines of `get_temperature_from_filter_ratio`.

**Comment by jslavin** [comment]
I'm okay with removing the leading xrt_ from the file names. As for xrt_teem the only issue would be for those transitioning from IDL, though the suggested name is explicit enough that it should be findable for those interested. I would want to run these changes by Kathy and maybe Mark as well.

**Comment by wtbarnes** [comment]
With respect to `xrt_teem`, as you say, I think the name itself should be explicit enough to indicate this. We can also add a note in the docstring that says this function is meant to provide functionality that is equivalent to `xrt_teem` in IDL.

**Comment by jslavin** [comment]
PR #196 dealt with this. xrt_teem renamed to temperature_from_filter_ratio
