### ISSUE TITLE
`xrt_deconvolve` and `xrt_remove_lightleak` are hard to find in `util`

### ISSUE THREAD

**Issue by wtbarnes** [HinodeXRT/xrtpy#182]
### Description

`util` subpackages are typically used for utility/misc functions are useful across subpackages. Putting `xrt_deconvolve` and `xrt_remove_lightleak` in `util` makes them harder for users to find. I would suggest putting them in their own subpackage (name TBD) to make them more visible to users.

**Comment by jslavin** [comment]
I'm okay with this in principle, though I don't have any good ideas yet for the name of the directory/subpackage. They both fall under the category of data correction for instrumental effects.
