### ISSUE TITLE
Can the `requirements` folder be removed?

### ISSUE THREAD

**Issue by wtbarnes** [HinodeXRT/xrtpy#200]
### Description

All of the dependencies for `xrtpy` are enumerated in `setup.cfg`. However, these are also mirrored (manually, seemingly) in `requirements` directory and the various files within this directory and it is not clear what purpose these files serve. Presumably, these need to be updated by hand each time the dependencies are updated in `setup.cfg` which creates the opportunity for these to be easily out of sync.

#37 seems to have very purposefully created this set of files as a mirror to what is in `setup.cfg`. However, it is not clear to me where exactly these files are being used. 

I am mainly raising this as an issue as the existence of these files created some confusion in #197 about exactly where the doc dependencies needed to be updated. If these are not actually being used by anything, I would suggest removing this whole directory.

**Comment by joyvelasquez** [comment]
@namurphy, I believe we can close this issue now, as it has been resolved with your PR #280 that removes requirements.txt.
