### ISSUE TITLE
[JOSS-Review 6396] Installation issues

### ISSUE THREAD

**Issue by dpshelio** [HinodeXRT/xrtpy#228]
### Description

Trying example used to generate figure figure 3 as explained in the docs [Using temperature_from_filter_ratio to analyze XRT data](https://xrtpy.readthedocs.io/en/stable/notebooks/data_analysis/Using_temperature_from_filter_ratio.html) in the docs, I get an error when importing sunpy because requests is missing. I believe, the dependencies should be `sunpy[all]` (or the minimum required)
https://github.com/HinodeXRT/xrtpy/blob/660a539f3d6c7ee1e4596e86d4fdbbed5d74871e/setup.cfg#L39

**Comment by Cadair** [comment]
You might not need `sunpy[all]` I think you at least need `sunpy[map]` as you [import map](https://github.com/HinodeXRT/xrtpy/blob/main/xrtpy/image_correction/remove_lightleak.py#L11) inside xrtpy itself. I would argue you don't need `sunpy[net]` to be included in the dependencies for xrtpy as you don't import it inside the module.

That being said, you do use it in the docs, so I would document it, and maybe mention it at the top of the examples that if a user installed xrtpy from pip they might need to install `sunpy[net]` to run this example.

**Comment by joyvelasquez** [comment]
Update the documentation to inform users about the optional dependencies. Made sure that requests and sunpy[map] are included in the install_requires section.
