### ISSUE TITLE
[JOSS-Review 6396] Functionality documentation

### ISSUE THREAD

**Issue by dpshelio** [HinodeXRT/xrtpy#230]
### Description

_Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?_

Some functions have very good documentation, e.g., [`xrtpy.response.temperature_from_filter_ratio.temperature_from_filter_ratio`](https://xrtpy.readthedocs.io/en/stable/api/xrtpy.response.temperature_from_filter_ratio.temperature_from_filter_ratio.html#xrtpy.response.temperature_from_filter_ratio.temperature_from_filter_ratio).

Some functions/methods/attributes have no documentation. For example: `xrtpy.response.TemperatureResponseFundamental().integration()`

The rest is somehow in between. It's quite difficult to get the way around the documentation as it's not provided in any order but as sphinx finds it.  I'd suggest providing some order through pages to make it easier for the contributors to find their way around it.

**Comment by Cadair** [comment]
I agree with this that the API documentation could use some improvements. I don't even see how to navigate to that link @dpshelio provided from the nav bar of the docs. I would like to see an API section of the docs listing all the API. You may want to look into autoapi or automodapi to help with that.
