### ISSUE TITLE
[JOSS-Review 6396] Community guidelines

### ISSUE THREAD

**Issue by dpshelio** [HinodeXRT/xrtpy#231]
### Description

_Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support_

Partially. 
- (2) and (3) is fulfilled under their [communications route](https://xrtpy.readthedocs.io/en/stable/feedback_communication.html) page, and though minimal, it provides the enough information.
- (1) is missing. Some basic description as provided by other related projects will be of great help here too.

**Comment by Cadair** [comment]
:+1: I agree the contributor guide could use a little extra info. It doesn't mention github for example :)

**Comment by joyvelasquez** [comment]
Updating contributing section PR #248

**Comment by joyvelasquez** [comment]
Thanks for noticing, we quickly lose sight of minor import meaningful things!
