### ISSUE TITLE
`pkg_resources` is deprecated

### ISSUE THREAD

**Issue by Cadair** [HinodeXRT/xrtpy#238]
### Description

In this example: https://xrtpy.readthedocs.io/en/stable/notebooks/data_analysis/Remove_lightleak.html you use the deprecated `pkg_resources`.

I would recommend rather than updating the package in that example that you make it so that there's a function to get the bundled data `xrtpy.data.get_data("image_correction/comp_XRT20150621_055911.7.fits")` or similar.

**Comment by namurphy** [comment]
Internally, we can switch to using [`importlib.resources`](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources).
