### ISSUE TITLE
Typo in one of the test files

### ISSUE THREAD

**Issue by adolliou** [HinodeXRT/xrtpy#239]
### Bug description

Hi everyone, 
First of all, thank you for this code.

While building another the repository ([synthesizAR](https://github.com/wtbarnes/synthesizAR)), I ran into an issue while the installing the main branch of xrtpy. 
It seems it was because of a typo in one of the test file. 

The file [Al_thick_22Sept2021_temperature_response_hybridtxt.txt](https://github.com/HinodeXRT/xrtpy/blob/main/xrtpy/response/tests/data/temperature_response_hybrid_IDL_testing_files/Al_thick/Al_thick_22Sept2021_temperature_response_hybridtxt.txt)

I believe it should be hybrid.txt ? 

For reference, installing xrtpy from pypi worked well, but installing from the main branch in the repo triggered the bug. 

Bests,

**Comment by joyvelasquez** [comment]
Hello @adolliou, thank you for catching this! We'll get on fixing this issue.
