### ISSUE TITLE
Astropy Time Support

### ISSUE THREAD

**Issue by DanRyanIrish** [HinodeXRT/xrtpy#78]
This issue is a suggested API change to support time inputs as `astropy.time.Time` objects.  Astropy time is now the standard way of expressing time in the sunpy ecosystem so many users may already have their times in Astropy time objects.

One way to go could be to simply add `astropy.time.Time` as a supported input.  Alternatively `astropy.time.Time` could be the only accepted format and your docs could show examples like
```python
>>> from sunpy.time import parse_time
>>> result = func(parse_time("2000-01-01T00:00"))
```
The latter case might reduce your maintenance burden but would be a breaking change.

**Comment by wtbarnes** [comment]
I'm a bit confused here. `parse_time` accepts `astropy.time.Time` objects and always returns `astropy.time.Time` objects so as long as everything passes through `parse_time`, I'm not sure where the problem lies?
