### ISSUE TITLE
setup.cfg includes deprecated configuration for pytest

### ISSUE THREAD

**Issue by jslavin** [HinodeXRT/xrtpy#92]
In setup.cfg there is the line:
looponfailroots =
    xrtpy

That seems to cause a deprecation warning by current versions of pytest:
DeprecationWarning: The --looponfail command line argument and looponfailroots config variable are deprecated.
  The loop-on-fail feature will be removed in pytest-xdist 4.0.
    config.issue_config_time_warning(warning, 2)

**Comment by namurphy** [comment]
Looks like we removed the deprecated `looponfailroots` option, so we can close this issue.
