### ISSUE TITLE
Temperature response returns all NaNs

### ISSUE THREAD

**Issue by wtbarnes** [HinodeXRT/xrtpy#97]
The `Temperature_Response_Fundamental.temperature_response()` returns all NaNs. This can be seen in the example gallery entry in the docs: https://xrtpy.readthedocs.io/en/latest/notebooks/computing_functions/temperature_response.html. I've tried a number of different dates and this always seems to return NaN independent of the date.

Some preliminary testing on my end shows that the NaN entries start appearing in `Temperature_Response_Fundamental.effective_area()` method which returns all NaNs. 

This wasn't caught by the tests because the temperature response tests are being skipped. See #98

**Comment by wtbarnes** [comment]
I've tracked this down to the `contamination_on_ccd` property on the `EffectiveAreaFundamental` object. This is an issue not just with the temperature response but also with the effective area calculation. I'm not completely sure why the effective area tests aren't failing as well.

The issue seems to be that when doing the interpolation, this warning arises,
```
/Users/wtbarnes/mambaforge/envs/xrtpy-dev/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py:653: RuntimeWarning: divide by zero encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
/Users/wtbarnes/mambaforge/envs/xrtpy-dev/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py:656: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo
```

This seems to be due to the fact that the the x coordinate being interpolated over (`ccd_data_dates_to_seconds`)
is not monotonic as seen in the plot below,

![image](https://user-images.githubusercontent.com/8676141/207409076-1f75ca41-6609-4926-86fc-486b31316c5d.png)

**Comment by joyvelasquez** [comment]
Hello @wtbarnes, thank you for the detail notes. I'm looking into the issue now and planning to update the notebooks as well.
